version: '2'

services:
  database:
    image: mysql:5.6.35
    container_name: mysql5.6
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      # https://github.com/docker-library/docs/tree/master/mysql#environment-variables
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
